// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7mNysy32mvJWjdRPtqsJPYJO3CQ_e6Y',
    appId: '1:484767174910:web:7dd907793ca3653322d5af',
    messagingSenderId: '484767174910',
    projectId: 'the-ideahub-app',
    authDomain: 'the-ideahub-app.firebaseapp.com',
    storageBucket: 'the-ideahub-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6yWvtykHBZqmKdQ3teWZDC35_5DMXYto',
    appId: '1:484767174910:android:334118b849d43dcd22d5af',
    messagingSenderId: '484767174910',
    projectId: 'the-ideahub-app',
    storageBucket: 'the-ideahub-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr7mNysy32mvJWjdRPtqsJPYJO3CQ_e6Y',
    appId: '1:484767174910:web:69315aa5937d668122d5af',
    messagingSenderId: '484767174910',
    projectId: 'the-ideahub-app',
    authDomain: 'the-ideahub-app.firebaseapp.com',
    storageBucket: 'the-ideahub-app.firebasestorage.app',
  );
}
